// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A node in the link graph, with display metadata for rendering.
 */
export type GraphNode = { 
/**
 * Relative note path.
 */
path: string, 
/**
 * Display title (frontmatter title, first heading, or filename).
 */
title: string, 
/**
 * Undirected link degree (forward links + backlinks).
 */
degree: number, 
/**
 * Frontmatter tags of the note.
 */
tags: Array<string>, 
/**
 * Last-modified time, whole seconds since the Unix epoch.
 */
mtime_secs: bigint, };
