// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bounds a graph request: a focus note + traversal depth, or global.
 */
export type GraphScope = { 
/**
 * The note to center the neighborhood on. `None` ⇒ the whole graph.
 */
focus: string | null, 
/**
 * Undirected hops from `focus` to include. `None` ⇒ 1.
 */
depth: number | null, };
