// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a successful query.
 */
export type QueryResponse = { "type": "note", 
/**
 * Full markdown contents.
 */
contents: string, } | { "type": "paths", 
/**
 * Relative note paths.
 */
paths: Array<string>, };
