// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An AI-suggested (not-yet-materialized) link between two notes. Track 2 shape.
 */
export type SuggestedEdge = { 
/**
 * Source note path.
 */
from: string, 
/**
 * Target note path.
 */
to: string, 
/**
 * Suggestion strength (relative ordering only).
 */
score: number, };
